### ISSUE TITLE
`app.use() requires middleware functions` error

### ISSUE THREAD

**Issue by Naoto-Ida** [LionC/express-basic-auth#1] opened 2017-04-11 02:31 UTC
I'm getting the error `app.use() requires middleware functions`.

```
{
"express": "4.14.0",
"express-basic-auth": "1.0.1"
}
```

**Comment by LionC** [comment] 2017-04-11 05:39
Thannks for reporting!

Can you add the full code snippet where you are calling app.use and configuring express-basic-auth, so I can reproduce and fix it?

**Comment by LionC** [comment] 2017-04-19 07:48
Closing for now, as the problem is not reproducable with the given infos.

**Closed by LionC** 2017-04-19 07:48 UTC
