### ISSUE TITLE
Challenge doesn't show up on lambda / serverless API

### ISSUE THREAD

**Issue by jakowenko** [LionC/express-basic-auth#42] opened 2022-01-31 19:24 UTC
I'm running an express API with an AWS Lambda proxy function using [@vendia/serverless-express](https://www.npmjs.com/package/@vendia/serverless-express). Locally the route produces the challenge prompt, but when deployed I only get the 401 unauthorized and am never prompted to enter the login information.

Does something else need to be done with serverless APIs or something specifically with AWS / Lambda?

```javascript
router.use(
    '/docs',
    basicAuth({
      users: { admin: 'supersecret' },
      challenge: true,
    }),
    swaggerUi.serve,
    swaggerUi.setup(spec, {
      swaggerOptions: { persistAuthorization: true },
    })
  );
```

**Comment by kmluns** [comment] 2022-11-22 17:59
Hey, I'm also looking for an answer. I also find that the problem was caused by the missing header `WWW-Authenticate: Basic`. So, the browser doesn't open the dialog for information. 

Also, AWS Lambda or Http Integration remapped the `WWW-Authenticate` header. [You can read here](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-known-issues.html). 

Also, you can follow [that](https://stackoverflow.com/a/58042589).

[This](https://stackoverflow.com/a/74295625) looks like a solution but is still a temporary and bad solution.

So, you must do `basic auth` on the HTTP layer in aws. 

Also, there is another [reading](https://medium.com/@Da_vidgf/http-basic-auth-with-api-gateway-and-serverless-5ae14ad0a270) for how you should do `basic auth` in AWS Serverless.

**Comment by LionC** [comment] 2023-09-28 13:57
See @kmluns answer, seems to be out of scope for this middleware.

**Closed as completed by LionC** 2023-09-28 13:57 UTC
